#!/bin/bash
# QA Bot GitHub Action Entrypoint
#
# Runs the QA bot CLI and handles GitHub-specific integrations:
# - Parses JSON results
# - Sets GitHub Action outputs
# - Posts PR comments
# - Sets exit code based on findings

set -e

echo "::group::QA Bot Configuration"
echo "URL: $INPUT_URL"
echo "Goal: $INPUT_GOAL"
echo "Max Agents: $INPUT_MAX_AGENTS"
echo "Max Cost: \$$INPUT_MAX_COST"
echo "Max Duration: $INPUT_MAX_DURATION minutes"
echo "Model: $INPUT_MODEL"
echo "Post Comment: $INPUT_POST_COMMENT"
echo "Fail on Critical: $INPUT_FAIL_ON_CRITICAL"
if [ -n "$INPUT_CREDENTIALS" ]; then
    echo "Credentials: [provided - $(echo "$INPUT_CREDENTIALS" | grep -c '=') key(s)]"
else
    echo "Credentials: [not provided]"
fi
if [ -n "$TESTMAIL_API_KEY" ] && [ -n "$TESTMAIL_NAMESPACE" ]; then
    echo "Email Testing: Enabled (Testmail.app)"
else
    echo "Email Testing: Disabled (no Testmail.app credentials)"
fi
if [ "$INPUT_DANGEROUSLY_SKIP_PERMISSIONS" = "true" ]; then
    echo "Skip Permissions: ENABLED (auto-approving all irreversible actions)"
else
    echo "Skip Permissions: Disabled (will pause for approval)"
fi
echo "::endgroup::"

# Handle credentials
CREDS_ARGS=""
if [ -n "$INPUT_CREDENTIALS" ]; then
    # Write credentials to temp file (secure - only accessible by this process)
    CREDS_FILE=$(mktemp)
    echo "$INPUT_CREDENTIALS" > "$CREDS_FILE"
    CREDS_ARGS="--credentials $CREDS_FILE"
fi

# Handle skip permissions flag
SKIP_PERMISSIONS_ARG=""
if [ "$INPUT_DANGEROUSLY_SKIP_PERMISSIONS" = "true" ]; then
    SKIP_PERMISSIONS_ARG="--dangerously-skip-permissions"
fi

# Run QA bot and capture output
echo "::group::Running QA Bot Exploration"
# shellcheck disable=SC2086
python -m qa_bot.cli "$INPUT_URL" \
    --goal "$INPUT_GOAL" \
    --max-agents "$INPUT_MAX_AGENTS" \
    --max-cost "$INPUT_MAX_COST" \
    --max-duration "$INPUT_MAX_DURATION" \
    --model "$INPUT_MODEL" \
    --output json \
    --output-file /tmp/qa-result.json \
    --log-level full \
    $CREDS_ARGS \
    $SKIP_PERMISSIONS_ARG || true
echo "::endgroup::"

# Clean up credentials file
if [ -n "$CREDS_FILE" ] && [ -f "$CREDS_FILE" ]; then
    rm -f "$CREDS_FILE"
fi

# Check if result file exists
if [ ! -f /tmp/qa-result.json ]; then
    echo "::error::QA Bot failed to produce results"
    exit 1
fi

# Parse results
REPORT=$(jq -r '.report // "No report generated"' /tmp/qa-result.json)
ISSUES_COUNT=$(jq -r '.issues_found // 0' /tmp/qa-result.json)
FLOWS_EXPLORED=$(jq -r '.flows_explored // 0' /tmp/qa-result.json)
DURATION=$(jq -r '.duration_seconds // 0' /tmp/qa-result.json)

# Count critical issues
CRITICAL_COUNT=$(jq -r '[.issues // [] | .[] | select(.severity == "critical" or .severity == "Critical")] | length' /tmp/qa-result.json)

echo "::group::Results Summary"
echo "Flows explored: $FLOWS_EXPLORED"
echo "Issues found: $ISSUES_COUNT"
echo "Critical issues: $CRITICAL_COUNT"
echo "Duration: ${DURATION}s"
echo "::endgroup::"

# Set GitHub Action outputs
# Using the recommended approach for multiline strings
{
    echo "report<<EOF"
    echo "$REPORT"
    echo "EOF"
} >> "$GITHUB_OUTPUT"

echo "issues-count=$ISSUES_COUNT" >> "$GITHUB_OUTPUT"
echo "critical-issues=$CRITICAL_COUNT" >> "$GITHUB_OUTPUT"
echo "flows-explored=$FLOWS_EXPLORED" >> "$GITHUB_OUTPUT"

# Post PR comment if requested
if [ "$INPUT_POST_COMMENT" = "true" ]; then
    echo "::group::Posting PR Comment"

    # Check if we have the event file and a PR context
    if [ -f "$GITHUB_EVENT_PATH" ]; then
        # Try to get PR number from various event types
        PR_NUMBER=$(jq -r '
            .pull_request.number //
            .issue.number //
            empty
        ' "$GITHUB_EVENT_PATH")

        if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ]; then
            echo "Posting comment to PR #$PR_NUMBER..."

            # Build comment body with proper escaping
            COMMENT_BODY=$(cat <<COMMENT_EOF
## QA Bot Report

$REPORT

---
**Summary:** Explored $FLOWS_EXPLORED user flows | Found $ISSUES_COUNT issues ($CRITICAL_COUNT critical) | Duration: ${DURATION}s

<sub>Generated by [QA Bot](https://github.com/integuide/qa-bot) using Claude AI</sub>
COMMENT_EOF
)

            # Post comment using GitHub API
            HTTP_STATUS=$(curl -s -o /tmp/comment-response.json -w "%{http_code}" -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \
                -d "$(jq -n --arg body "$COMMENT_BODY" '{body: $body}')")

            if [ "$HTTP_STATUS" = "201" ]; then
                COMMENT_URL=$(jq -r '.html_url' /tmp/comment-response.json)
                echo "Comment posted successfully: $COMMENT_URL"
            else
                echo "::warning::Failed to post comment (HTTP $HTTP_STATUS)"
                cat /tmp/comment-response.json
            fi
        else
            echo "No PR number found in event context, skipping comment"
        fi
    else
        echo "No GitHub event file found, skipping comment"
    fi
    echo "::endgroup::"
fi

# Determine exit code
EXIT_CODE=0

if [ "$INPUT_FAIL_ON_CRITICAL" = "true" ] && [ "$CRITICAL_COUNT" -gt 0 ]; then
    echo "::error::Found $CRITICAL_COUNT critical issues"
    EXIT_CODE=1
fi

# Print report to logs for visibility
echo "::group::Full QA Report"
echo "$REPORT"
echo "::endgroup::"

exit $EXIT_CODE
