# QA Bot - On-Demand via PR Comment
#
# This workflow allows users to request QA testing by commenting
# "@QABot https://example.com" on any pull request.
#
# Setup:
# 1. Copy this file to .github/workflows/qa-bot-on-demand.yml
# 2. Add ANTHROPIC_API_KEY to repository secrets
# 3. Comment "@QABot https://your-url.com" on any PR

name: QA Bot (On-Demand)

on:
  issue_comment:
    types: [created]

jobs:
  qa-test:
    # Only run if comment mentions @QABot with a URL and is on a PR
    if: |
      contains(github.event.comment.body, '@QABot') &&
      github.event.issue.pull_request

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Extract URL from comment
        id: extract
        run: |
          # Extract first URL from comment body
          URL=$(echo "${{ github.event.comment.body }}" | grep -oP 'https?://[^\s]+' | head -1)

          if [ -z "$URL" ]; then
            echo "::error::No URL found in comment. Usage: @QABot https://your-url.com"
            exit 1
          fi

          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "Found URL: $URL"

      - name: Acknowledge request
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 Starting QA Bot exploration of `${{ steps.extract.outputs.url }}`...\n\nThis may take several minutes. Results will be posted when complete.'
            })

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR details
        id: pr-details
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          PR_JSON=$(gh pr view $PR_NUMBER --json title,body)
          PR_TITLE=$(echo "$PR_JSON" | jq -r '.title')
          PR_BODY=$(echo "$PR_JSON" | jq -r '.body' | head -c 2000)
          echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT
          {
            echo "pr_body<<EOF"
            echo "$PR_BODY"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Generate testing goal from PR
        id: generate-goal
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Escape special characters for JSON
          PR_TITLE=$(echo '${{ steps.pr-details.outputs.pr_title }}' | jq -Rs '.')
          PR_BODY=$(echo '${{ steps.pr-details.outputs.pr_body }}' | jq -Rs '.')

          RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
            -H "x-api-key: $ANTHROPIC_API_KEY" \
            -H "anthropic-version: 2023-06-01" \
            -H "content-type: application/json" \
            -d "{
              \"model\": \"claude-haiku-4-5\",
              \"max_tokens\": 200,
              \"messages\": [{
                \"role\": \"user\",
                \"content\": \"Convert this PR description into a concise QA testing goal (1-2 sentences). Focus on what user flows and functionality should be tested. If the PR description is empty or unclear, return a general exploration goal.\n\nPR Title: ${PR_TITLE}\n\nPR Body:\n${PR_BODY}\"
              }]
            }")

          GOAL=$(echo "$RESPONSE" | jq -r '.content[0].text // "Explore user flows and find bugs, broken elements, or usability problems."')
          echo "goal=$GOAL" >> $GITHUB_OUTPUT
          echo "Generated goal: $GOAL"

      - name: Run QA Bot
        id: qa
        uses: ./qa-bot/action
        with:
          url: ${{ steps.extract.outputs.url }}
          goal: ${{ steps.generate-goal.outputs.goal }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          max-duration: '10'
          fail-on-critical: 'false'  # Don't fail, just report

      - name: Summary
        run: |
          echo "### QA Bot Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Flows explored:** ${{ steps.qa.outputs.flows-explored }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Issues found:** ${{ steps.qa.outputs.issues-count }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Critical issues:** ${{ steps.qa.outputs.critical-issues }}" >> $GITHUB_STEP_SUMMARY
