# QA Bot - Staging to Production
#
# This workflow runs QA testing when:
# 1. A PR is opened from staging -> production
# 2. Someone comments "@QABot" on a staging -> production PR
#
# Setup:
# 1. Copy this file to .github/workflows/qa-bot-staging-to-prod.yml
# 2. Add ANTHROPIC_API_KEY to repository secrets
# 3. Add QA_BOT_TARGET_URL as a repository variable (Settings > Variables)
#
# Note: This example uses lighter settings (3 agents, 15 min) than the main
# workflow (5 agents, 20 min) for faster/cheaper runs. Adjust as needed.

name: QA Bot - Staging to Production

on:
  pull_request:
    types: [opened]
    branches:
      - production

  issue_comment:
    types: [created]

# Only run one QA test at a time per PR
concurrency:
  group: qa-bot-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: true

jobs:
  qa-test:
    # Run if:
    # 1. PR opened from staging branch, OR
    # 2. Comment contains @QABot on a PR from staging
    if: |
      (github.event_name == 'pull_request' && github.head_ref == 'staging') ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@QABot'))

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      reactions: write  # For adding rocket emoji to triggering comment

    steps:
      # For comment triggers, verify it's a staging -> production PR
      - name: Get PR details (comment trigger)
        if: github.event_name == 'issue_comment'
        id: pr-details
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const isFromStaging = pr.head.ref === 'staging';
            const isToProduction = pr.base.ref === 'production';
            const isValid = isFromStaging && isToProduction;

            if (!isValid) {
              core.setOutput('valid', 'false');
              return;
            }

            core.setOutput('valid', 'true');
            core.setOutput('ref', pr.head.sha);

            // Add rocket reaction to show we're working on it
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });

      # This step is for logging only - subsequent steps are gated by their own conditions
      - name: Skip (not staging -> production)
        if: github.event_name == 'issue_comment' && steps.pr-details.outputs.valid == 'false'
        run: |
          echo "::notice::@QABot only runs on PRs from staging to production"

      - name: Check for target URL
        if: github.event_name == 'pull_request' || steps.pr-details.outputs.valid == 'true'
        run: |
          if [ -z "${{ vars.QA_BOT_TARGET_URL }}" ]; then
            echo "::error::QA_BOT_TARGET_URL not configured. Go to Settings > Variables to add it."
            exit 1
          fi
          echo "Target URL: ${{ vars.QA_BOT_TARGET_URL }}"

      - name: Checkout repository
        if: github.event_name == 'pull_request' || steps.pr-details.outputs.valid == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr-details.outputs.ref || github.event.pull_request.head.sha }}

      - name: Run QA Bot
        id: qa
        uses: ./qa-bot/action
        with:
          url: ${{ vars.QA_BOT_TARGET_URL }}
          goal: 'Test critical user flows before production deployment'
          max-agents: '3'
          max-duration: '15'
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          fail-on-critical: 'true'

      - name: Summary
        run: |
          echo "### QA Bot Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Target:** ${{ vars.QA_BOT_TARGET_URL }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Flows Explored | ${{ steps.qa.outputs.flows-explored }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Issues Found | ${{ steps.qa.outputs.issues-count }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Critical Issues | ${{ steps.qa.outputs.critical-issues }} |" >> $GITHUB_STEP_SUMMARY
